name: Deploy to One.com

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Install and build
      run: npm install && npm run build

    - name: GitHub Deploy to One.com
      uses: rostimelk/one.com-deployer@master
      env:
          ONE_DOMAIN_NAME: krogolsen.dk
          ONE_SSH_KEY_PUBLIC: ${{ secrets.PUBLIC_KEY_NAME }}
          ONE_SSH_KEY_PRIVATE: ${{ secrets.PRIVATE_KEY_NAME }}
          TPO_SRC_PATH: "./build/"
          TPO_PATH: "/flemming"
